server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# 数据库连接配置
database:
  logger:
    path:    "logs/sql"
    level:   "all"
    stdout:  true
    ctxKeys: ["RequestId"]

  default:
    link:   "mysql:root:123456@tcp(localhost:3306)/erp"
    debug:  true

# Redis配置
redis:
  default:
    address: localhost:6379
    db:      0

app:
  path: "D:/Files/erp/"
  temp: "D:/Files/erp/temp/"