// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "goframe-erp-v1/internal/logic/access"
	_ "goframe-erp-v1/internal/logic/file"
	_ "goframe-erp-v1/internal/logic/middleware"
	_ "goframe-erp-v1/internal/logic/role"
	_ "goframe-erp-v1/internal/logic/supplier"
	_ "goframe-erp-v1/internal/logic/user"
)
