// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "goframe-erp-v1/internal/logic/middleware"
	_ "goframe-erp-v1/internal/logic/user"
)
