// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Customer is the golang structure of table customer for DAO operations like Where/Data.
type Customer struct {
	g.Meta            `orm:"table:customer, do:true"`
	CustomerId        interface{} // 客户ID
	CustomerName      interface{} // 客户名称
	CustomerDesc      interface{} // 客户描述
	CustomerTelephone interface{} // 客户座机号码
	CustomerPhone     interface{} // 客户手机号码
	CustomerAddress   interface{} // 客户地址
	CustomerStatus    interface{} // 客户状态
}
