// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// GoodsSupplierRel is the golang structure of table goods_supplier_rel for DAO operations like Where/Data.
type GoodsSupplierRel struct {
	g.Meta      `orm:"table:goods_supplier_rel, do:true"`
	RelId       interface{} // 关联ID
	GoodsId     interface{} // 关联商品ID
	SupplierId  interface{} // 关联供应商ID
	SupplyPrice interface{} // 供应价格
}
