// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Goods is the golang structure of table goods for DAO operations like Where/Data.
type Goods struct {
	g.Meta      `orm:"table:goods, do:true"`
	GoodsId     interface{} // 商品ID
	GoodsName   interface{} // 商品名称
	GoodsDesc   interface{} // 商品描述
	GoodsUnit   interface{} // 商品单位
	GoodsPrice  interface{} // 商品售价
	GoodsImg    interface{} // 商品主图
	GoodsStatus interface{} // 商品状态
}
