// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Inventory is the golang structure of table inventory for DAO operations like Where/Data.
type Inventory struct {
	g.Meta   `orm:"table:inventory, do:true"`
	GoodsId  interface{} // 商品ID
	Quantity interface{} // 库存数量
	Amount   interface{} // 总金额
	Price    interface{} // 单位金额
}
