// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Inventory is the golang structure of table inventory for DAO operations like Where/Data.
type Inventory struct {
	g.Meta    `orm:"table:inventory, do:true"`
	GoodsId   interface{} // 库存商品ID
	GoodsCost interface{} // 商品成本
	Quantity  interface{} // 库存数量
}
