// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// OrderItem is the golang structure of table order_item for DAO operations like Where/Data.
type OrderItem struct {
	g.Meta   `orm:"table:order_item, do:true"`
	OrderNo  interface{} // 单号
	GoodsId  interface{} // 商品ID
	Price    interface{} // 单价
	Amount   interface{} // 订单项总价格
	Quantity interface{} // 数量
	Notes    interface{} // 备注
}
