// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// OrderItem is the golang structure of table order_item for DAO operations like Where/Data.
type OrderItem struct {
	g.Meta          `orm:"table:order_item, do:true"`
	OrderItemId     interface{} // 订单项ID
	OrderId         interface{} // 订单ID
	GoodsId         interface{} // 商品ID
	GoodsName       interface{} // 商品名称
	Quantity        interface{} // 订购数量
	GoodsPrice      interface{} // 商品原价
	ActualPrice     interface{} // 实际售价
	OrderItemAmount interface{} // 订单项总额
	OrderItemStatus interface{} // 订单项状态
}
