// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Order is the golang structure of table order for DAO operations like Where/Data.
type Order struct {
	g.Meta            `orm:"table:order, do:true"`
	OrderId           interface{} // 订单ID
	OrderNum          interface{} // 订单号
	OrderTime         *gtime.Time // 订单时间
	OrderType         interface{} // 订单类型
	OrderSupplier     interface{} // 订单供应商
	OrderSupplierName interface{} // 订单供应商名称
	OrderCustomer     interface{} // 订单客户
	OrderCustomerName interface{} // 订单客户名称
	OrderAmount       interface{} // 订单总额
	OrderStatus       interface{} // 订单状态
}
