// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Supplier is the golang structure of table supplier for DAO operations like Where/Data.
type Supplier struct {
	g.Meta            `orm:"table:supplier, do:true"`
	SupplierId        interface{} // 供应商ID
	SupplierName      interface{} // 供应商名称
	SupplierDesc      interface{} // 供应商描述
	SupplierTelephone interface{} // 供应商座机号码
	SupplierPhone     interface{} // 供应商手机号码
	SupplierAddress   interface{} // 供应商地址
	SupplierStatus    interface{} // 供应商状态
}
