// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SysRoleAccess is the golang structure of table sys_role_access for DAO operations like Where/Data.
type SysRoleAccess struct {
	g.Meta       `orm:"table:sys_role_access, do:true"`
	RoleAccessId interface{} // 角色权限关联ID
	RoleId       interface{} // 关联角色ID
	AccessId     interface{} // 关联权限ID
}
