// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysLog is the golang structure of table sys_log for DAO operations like Where/Data.
type SysLog struct {
	g.Meta   `orm:"table:sys_log, do:true"`
	LogId    interface{} // 日志ID
	UserId   interface{} // 操作者ID
	FromIp   interface{} // 操作者IP
	Uri      interface{} // 访问uri
	LogTime  *gtime.Time // 访问时间
	LogType  interface{} // 日志级别
	LogError interface{} // 日志错误信息
}
