// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SysUserRole is the golang structure of table sys_user_role for DAO operations like Where/Data.
type SysUserRole struct {
	g.Meta     `orm:"table:sys_user_role, do:true"`
	UserRoleId interface{} // 用户角色关联ID
	UserId     interface{} // 关联用户
	RoleId     interface{} // 关联角色
}
