// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SysUser is the golang structure of table sys_user for DAO operations like Where/Data.
type SysUser struct {
	g.Meta       `orm:"table:sys_user, do:true"`
	UserId       interface{} // 用户ID，主键
	UserName     interface{} // 登录用户名
	UserPassword interface{} // 登录密码，md5加密
	UserRealName interface{} // 用户真实姓名
	UserPhone    interface{} // 用户手机号，11位数字
	UserImage    interface{} // 用户头像url
	UserStatus   interface{} // 用户状态
}
