// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SysFile is the golang structure of table sys_file for DAO operations like Where/Data.
type SysFile struct {
	g.Meta   `orm:"table:sys_file, do:true"`
	FileMd5  interface{} // 文件MD5
	FileName interface{} // 文件名(UUID)
}
