// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SysAccess is the golang structure of table sys_access for DAO operations like Where/Data.
type SysAccess struct {
	g.Meta      `orm:"table:sys_access, do:true"`
	AccessId    interface{} // 权限ID
	AccessTitle interface{} // 权限标题
	AccessUri   interface{} // 权限路径
}
