// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// GoodsSupplierRelDao is the data access object for table goods_supplier_rel.
type GoodsSupplierRelDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns GoodsSupplierRelColumns // columns contains all the column names of Table for convenient usage.
}

// GoodsSupplierRelColumns defines and stores column names for table goods_supplier_rel.
type GoodsSupplierRelColumns struct {
	RelId       string // 关联ID
	GoodsId     string // 关联商品ID
	SupplierId  string // 关联供应商ID
	SupplyPrice string // 供应价格
}

// goodsSupplierRelColumns holds the columns for table goods_supplier_rel.
var goodsSupplierRelColumns = GoodsSupplierRelColumns{
	RelId:       "rel_id",
	GoodsId:     "goods_id",
	SupplierId:  "supplier_id",
	SupplyPrice: "supply_price",
}

// NewGoodsSupplierRelDao creates and returns a new DAO object for table data access.
func NewGoodsSupplierRelDao() *GoodsSupplierRelDao {
	return &GoodsSupplierRelDao{
		group:   "default",
		table:   "goods_supplier_rel",
		columns: goodsSupplierRelColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *GoodsSupplierRelDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *GoodsSupplierRelDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *GoodsSupplierRelDao) Columns() GoodsSupplierRelColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *GoodsSupplierRelDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *GoodsSupplierRelDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *GoodsSupplierRelDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
