// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PurchaseOrderDao is the data access object for table purchase_order.
type PurchaseOrderDao struct {
	table   string               // table is the underlying table name of the DAO.
	group   string               // group is the database configuration group name of current DAO.
	columns PurchaseOrderColumns // columns contains all the column names of Table for convenient usage.
}

// PurchaseOrderColumns defines and stores column names for table purchase_order.
type PurchaseOrderColumns struct {
	OrderId       string // 单据ID
	OrderNo       string // 单号
	SupplierId    string // 供应商ID
	SupplierName  string // 供应商名称
	OrderQuantity string // 采购数量
	OrderAmount   string // 采购总金额
	CreateTime    string // 制单时间
	CreateUser    string // 制单人
	CompleteTime  string // 完成时间
	CompleteUser  string // 操作员
	Notes         string // 备注
	OrderStatus   string // 单据状态
}

// purchaseOrderColumns holds the columns for table purchase_order.
var purchaseOrderColumns = PurchaseOrderColumns{
	OrderId:       "order_id",
	OrderNo:       "order_no",
	SupplierId:    "supplier_id",
	SupplierName:  "supplier_name",
	OrderQuantity: "order_quantity",
	OrderAmount:   "order_amount",
	CreateTime:    "create_time",
	CreateUser:    "create_user",
	CompleteTime:  "complete_time",
	CompleteUser:  "complete_user",
	Notes:         "notes",
	OrderStatus:   "order_status",
}

// NewPurchaseOrderDao creates and returns a new DAO object for table data access.
func NewPurchaseOrderDao() *PurchaseOrderDao {
	return &PurchaseOrderDao{
		group:   "default",
		table:   "purchase_order",
		columns: purchaseOrderColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PurchaseOrderDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PurchaseOrderDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PurchaseOrderDao) Columns() PurchaseOrderColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PurchaseOrderDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PurchaseOrderDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PurchaseOrderDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
