// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"goframe-erp-v1/internal/model"
)

type (
	IAccess interface {
		GetAccessList() (out model.GetAccessListOutput, err error)
		GetAccessById(in model.GetAccessByIdInput) (out model.GetAccessByIdOutput, err error)
		AddAccess(ctx context.Context, in model.AddAccessInput) (out model.AddAccessOutput, err error)
		UpdateAccess(ctx context.Context, in model.UpdateAccessInput) (err error)
		DeleteAccess(ctx context.Context, in model.DeleteAccessInput) (err error)
	}
)

var (
	localAccess IAccess
)

func Access() IAccess {
	if localAccess == nil {
		panic("implement not found for interface IAccess, forgot register?")
	}
	return localAccess
}

func RegisterAccess(i IAccess) {
	localAccess = i
}
