// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"goframe-erp-v1/internal/model/pojo"
)

type (
	ICustomer interface {
		GetCustomerList(ctx context.Context) (out pojo.GetCustomerListOutput, err error)
		UpdateCustomer(ctx context.Context, in pojo.UpdateCustomerInput) (err error)
		AddCustomer(ctx context.Context, in pojo.AddCustomerInput) (out pojo.AddCustomerOutput, err error)
		GetCustomerById(ctx context.Context, in pojo.GetCustomerByIdInput) (out pojo.GetCustomerByIdOutput, err error)
		CheckCustomerEnabled(ctx context.Context, customerId int64) (enabled bool, err error)
	}
)

var (
	localCustomer ICustomer
)

func Customer() ICustomer {
	if localCustomer == nil {
		panic("implement not found for interface ICustomer, forgot register?")
	}
	return localCustomer
}

func RegisterCustomer(i ICustomer) {
	localCustomer = i
}
