// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"goframe-erp-v1/internal/model"
)

type (
	ICustomer interface {
		GetCustomerList(ctx context.Context) (out model.GetCustomerListOutput, err error)
		UpdateCustomer(ctx context.Context, in model.UpdateCustomerInput) (err error)
		AddCustomer(ctx context.Context, in model.AddCustomerInput) (out model.AddCustomerOutput, err error)
		GetCustomerById(ctx context.Context, in model.GetCustomerByIdInput) (out model.GetCustomerByIdOutput, err error)
	}
)

var (
	localCustomer ICustomer
)

func Customer() ICustomer {
	if localCustomer == nil {
		panic("implement not found for interface ICustomer, forgot register?")
	}
	return localCustomer
}

func RegisterCustomer(i ICustomer) {
	localCustomer = i
}
