// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"goframe-erp-v1/internal/model"
)

type (
	IInventory interface {
		CheckInventory(ctx context.Context, in model.CheckInventoryInput) (out model.CheckInventoryOutput, err error)
		DeleteInventory(ctx context.Context, in model.DeleteInventoryInput) (err error)
		AddInventory(ctx context.Context, in model.AddInventoryInput) (err error)
		UpdateInventory(ctx context.Context, in model.UpdateInventoryInput) (err error)
		ReduceInventory(ctx context.Context, in model.ReduceInventoryInput) (err error)
		GetGoodsInventory(ctx context.Context, in model.GetGoodsInventoryInput) (out model.GetGoodsInventoryOutput, err error)
		GetInventoryStatistic(ctx context.Context) (out model.GetInventoryStatisticOutput, err error)
	}
)

var (
	localInventory IInventory
)

func Inventory() IInventory {
	if localInventory == nil {
		panic("implement not found for interface IInventory, forgot register?")
	}
	return localInventory
}

func RegisterInventory(i IInventory) {
	localInventory = i
}
