// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"goframe-erp-v1/internal/model/pojo"
)

type (
	IInventory interface {
		GetGoodsInventory(ctx context.Context, in pojo.GetGoodsInventoryInput) (out pojo.GetGoodsInventoryOutput, err error)
		GetInventoryList(ctx context.Context, in pojo.GetInventoryListInput) (out pojo.GetInventoryListOutput, err error)
		AddInventory(ctx context.Context, in pojo.AddInventoryInput) (out pojo.AddInventoryOutput, err error)
		ReduceInventory(ctx context.Context, in pojo.ReduceInventoryInput) (out pojo.ReduceInventoryOutput, err error)
	}
)

var (
	localInventory IInventory
)

func Inventory() IInventory {
	if localInventory == nil {
		panic("implement not found for interface IInventory, forgot register?")
	}
	return localInventory
}

func RegisterInventory(i IInventory) {
	localInventory = i
}
