// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"goframe-erp-v1/internal/model"

	"github.com/gogf/gf/v2/os/gtime"
)

type (
	IOrder interface {
		GenerateOrderNo(orderType int, time *gtime.Time) (orderNo string)
		RegisterType(orderType int, i model.InterfaceOrder)
		Type(orderType int) (i model.InterfaceOrder)
	}
)

var (
	localOrder IOrder
)

func Order() IOrder {
	if localOrder == nil {
		panic("implement not found for interface IOrder, forgot register?")
	}
	return localOrder
}

func RegisterOrder(i IOrder) {
	localOrder = i
}
