// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"goframe-erp-v1/internal/model/pojo/order"
)

type (
	IOrder interface {
		GetInventoryOrder(ctx context.Context, in order.GetInventoryOrderInput) (out order.GetInventoryOrderOutput, err error)
		GetInventoryOrderList(ctx context.Context, in order.GetInventoryOrderListInput) (out order.GetInventoryOrderListOutput, err error)
		CreateInventoryOrder(ctx context.Context, in order.CreateInventoryOrderInput) (out order.CreateInventoryOrderOutput, err error)
		CancelCreateInventoryOrder(ctx context.Context, in order.CancelCreateInventoryOrderInput) (err error)
		GetPurchaseOrder(ctx context.Context, in order.GetPurchaseOrderInput) (out order.GetPurchaseOrderOutput, err error)
		GetPurchaseOrderList(ctx context.Context, in order.GetPurchaseOrderListInput) (out order.GetPurchaseOrderListOutput, err error)
		CreatePurchaseOrder(ctx context.Context, in order.CreatePurchaseOrderInput) (out order.CreatePurchaseOrderOutput, err error)
		GetSaleOrder(ctx context.Context, in order.GetSaleOrderInput) (out order.GetSaleOrderOutput, err error)
		GetSaleOrderList(ctx context.Context, in order.GetSaleOrderListInput) (out order.GetSaleOrderListOutput, err error)
		CreateSaleOrder(ctx context.Context, in order.CreateSaleOrderInput) (out order.CreateSaleOrderOutput, err error)
	}
)

var (
	localOrder IOrder
)

func Order() IOrder {
	if localOrder == nil {
		panic("implement not found for interface IOrder, forgot register?")
	}
	return localOrder
}

func RegisterOrder(i IOrder) {
	localOrder = i
}
