// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"goframe-erp-v1/internal/model"
)

type (
	IRole interface {
		GetRoleList(ctx context.Context) (out model.GetRoleListOutput, err error)
		GetRoleById(ctx context.Context, in model.GetRoleByIdInput) (out model.GetRoleByIdOutput, err error)
		AddRole(ctx context.Context, in model.AddRoleInput) (out model.AddRoleOutput, err error)
		UpdateRole(ctx context.Context, in model.UpdateRoleInput) (err error)
		DeleteRole(ctx context.Context, in model.DeleteRoleInput) (err error)
		AddRoleAccess(ctx context.Context, in model.AddRoleAccessInput) (err error)
		DeleteRoleAccess(ctx context.Context, in model.DeleteRoleAccessInput) (err error)
		GetRoleAccessList(ctx context.Context, in model.GetRoleAccessListInput) (out model.GetRoleAccessListOutput, err error)
	}
)

var (
	localRole IRole
)

func Role() IRole {
	if localRole == nil {
		panic("implement not found for interface IRole, forgot register?")
	}
	return localRole
}

func RegisterRole(i IRole) {
	localRole = i
}
