// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"goframe-erp-v1/internal/model/pojo"
)

type (
	IRole interface {
		GetRoleList() (out pojo.GetRoleListOutput, err error)
		GetRoleById(in pojo.GetRoleByIdInput) (out pojo.GetRoleByIdOutput, err error)
		AddRole(ctx context.Context, in pojo.AddRoleInput) (out pojo.AddRoleOutput, err error)
		UpdateRole(ctx context.Context, in pojo.UpdateRoleInput) (err error)
		DeleteRole(ctx context.Context, in pojo.DeleteRoleInput) (err error)
		AddRoleAccess(ctx context.Context, in pojo.AddRoleAccessInput) (err error)
		DeleteRoleAccess(ctx context.Context, in pojo.DeleteRoleAccessInput) (err error)
		GetRoleAccessList(ctx context.Context, in pojo.GetRoleAccessListInput) (out pojo.GetRoleAccessListOutput, err error)
	}
)

var (
	localRole IRole
)

func Role() IRole {
	if localRole == nil {
		panic("implement not found for interface IRole, forgot register?")
	}
	return localRole
}

func RegisterRole(i IRole) {
	localRole = i
}
