// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"goframe-erp-v1/internal/model"
)

type (
	ISupplier interface {
		GetSupplierList(ctx context.Context) (out model.GetSupplierListOutput, err error)
		UpdateSupplier(ctx context.Context, in model.UpdateSupplierInput) (err error)
		AddSupplier(ctx context.Context, in model.AddSupplierInput) (out model.AddSupplierOutput, err error)
		GetSupplierById(ctx context.Context, in model.GetSupplierByIdInput) (out model.GetSupplierByIdOutput, err error)
	}
)

var (
	localSupplier ISupplier
)

func Supplier() ISupplier {
	if localSupplier == nil {
		panic("implement not found for interface ISupplier, forgot register?")
	}
	return localSupplier
}

func RegisterSupplier(i ISupplier) {
	localSupplier = i
}
