// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"goframe-erp-v1/internal/model/pojo"
)

type (
	ISupplier interface {
		GetSupplierList(ctx context.Context) (out pojo.GetSupplierListOutput, err error)
		UpdateSupplier(ctx context.Context, in pojo.UpdateSupplierInput) (err error)
		AddSupplier(ctx context.Context, in pojo.AddSupplierInput) (out pojo.AddSupplierOutput, err error)
		GetSupplierById(ctx context.Context, in pojo.GetSupplierByIdInput) (out pojo.GetSupplierByIdOutput, err error)
		CheckSupplierEnabled(ctx context.Context, supplierId int64) (enabled bool, err error)
	}
)

var (
	localSupplier ISupplier
)

func Supplier() ISupplier {
	if localSupplier == nil {
		panic("implement not found for interface ISupplier, forgot register?")
	}
	return localSupplier
}

func RegisterSupplier(i ISupplier) {
	localSupplier = i
}
