// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"goframe-erp-v1/internal/model"
)

type (
	IUser interface {
		GetUserById(ctx context.Context, in model.GetUserByIdInput) (out model.GetUserByIdOutput, err error)
		GetUserByUserName(ctx context.Context, in model.GetUserByUserNameInput) (out model.GetUserByUserNameOutput, err error)
		GetUserList(ctx context.Context) (out model.GetUserListOutput, err error)
		UserLogin(ctx context.Context, in model.UserLoginInput) (out model.UserLoginOutput, err error)
		UpdateUser(ctx context.Context, in model.UpdateUserInput) (err error)
		AddUser(ctx context.Context, in model.AddUserInput) (out model.AddUserOutput, err error)
		GetUserAccessList(ctx context.Context, in model.GetUserAccessListInput) (out model.GetUserAccessListOutput, err error)
		AddUserRole(ctx context.Context, in model.AddUserRoleInput) (err error)
		DeleteUserRole(ctx context.Context, in model.DeleteUserRoleInput) (err error)
		GetUserRoleList(ctx context.Context, in model.GetUserRoleListInput) (out model.GetUserRoleListOutput, err error)
	}
)

var (
	localUser IUser
)

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
