// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-erp-v1/internal/dao/internal"
)

// internalGoodsDao is internal type for wrapping internal DAO implements.
type internalGoodsDao = *internal.GoodsDao

// goodsDao is the data access object for table goods.
// You can define custom methods on it to extend its functionality as you wish.
type goodsDao struct {
	internalGoodsDao
}

var (
	// Goods is globally public accessible object for table goods operations.
	Goods = goodsDao{
		internal.NewGoodsDao(),
	}
)

// Fill with you ideas below.
