// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-erp-v1/internal/dao/internal"
)

// internalGoodsSupplierRelDao is internal type for wrapping internal DAO implements.
type internalGoodsSupplierRelDao = *internal.GoodsSupplierRelDao

// goodsSupplierRelDao is the data access object for table goods_supplier_rel.
// You can define custom methods on it to extend its functionality as you wish.
type goodsSupplierRelDao struct {
	internalGoodsSupplierRelDao
}

var (
	// GoodsSupplierRel is globally public accessible object for table goods_supplier_rel operations.
	GoodsSupplierRel = goodsSupplierRelDao{
		internal.NewGoodsSupplierRelDao(),
	}
)

// Fill with you ideas below.
