// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-erp-v1/internal/dao/internal"
)

// internalInventoryOrderDao is internal type for wrapping internal DAO implements.
type internalInventoryOrderDao = *internal.InventoryOrderDao

// inventoryOrderDao is the data access object for table inventory_order.
// You can define custom methods on it to extend its functionality as you wish.
type inventoryOrderDao struct {
	internalInventoryOrderDao
}

var (
	// InventoryOrder is globally public accessible object for table inventory_order operations.
	InventoryOrder = inventoryOrderDao{
		internal.NewInventoryOrderDao(),
	}
)

// Fill with you ideas below.
