// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-erp-v1/internal/dao/internal"
)

// internalReturnOrderDao is internal type for wrapping internal DAO implements.
type internalReturnOrderDao = *internal.ReturnOrderDao

// returnOrderDao is the data access object for table return_order.
// You can define custom methods on it to extend its functionality as you wish.
type returnOrderDao struct {
	internalReturnOrderDao
}

var (
	// ReturnOrder is globally public accessible object for table return_order operations.
	ReturnOrder = returnOrderDao{
		internal.NewReturnOrderDao(),
	}
)

// Fill with you ideas below.
