// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-erp-v1/internal/dao/internal"
)

// internalSaleOrderDao is internal type for wrapping internal DAO implements.
type internalSaleOrderDao = *internal.SaleOrderDao

// saleOrderDao is the data access object for table sale_order.
// You can define custom methods on it to extend its functionality as you wish.
type saleOrderDao struct {
	internalSaleOrderDao
}

var (
	// SaleOrder is globally public accessible object for table sale_order operations.
	SaleOrder = saleOrderDao{
		internal.NewSaleOrderDao(),
	}
)

// Fill with you ideas below.
