// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-erp-v1/internal/dao/internal"
)

// internalSupplierDao is internal type for wrapping internal DAO implements.
type internalSupplierDao = *internal.SupplierDao

// supplierDao is the data access object for table supplier.
// You can define custom methods on it to extend its functionality as you wish.
type supplierDao struct {
	internalSupplierDao
}

var (
	// Supplier is globally public accessible object for table supplier operations.
	Supplier = supplierDao{
		internal.NewSupplierDao(),
	}
)

// Fill with you ideas below.
