// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-erp-v1/internal/dao/internal"
)

// internalSysRoleAccessDao is internal type for wrapping internal DAO implements.
type internalSysRoleAccessDao = *internal.SysRoleAccessDao

// sysRoleAccessDao is the data access object for table sys_role_access.
// You can define custom methods on it to extend its functionality as you wish.
type sysRoleAccessDao struct {
	internalSysRoleAccessDao
}

var (
	// SysRoleAccess is globally public accessible object for table sys_role_access operations.
	SysRoleAccess = sysRoleAccessDao{
		internal.NewSysRoleAccessDao(),
	}
)

// Fill with you ideas below.
