// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Customer is the golang structure for table customer.
type Customer struct {
	CustomerId        int64  `json:"customerId"        ` // 客户ID
	CustomerName      string `json:"customerName"      ` // 客户名称
	CustomerDesc      string `json:"customerDesc"      ` // 客户描述
	CustomerTelephone string `json:"customerTelephone" ` // 客户座机号码
	CustomerPhone     string `json:"customerPhone"     ` // 客户手机号码
	CustomerAddress   string `json:"customerAddress"   ` // 客户地址
	CustomerStatus    int    `json:"customerStatus"    ` // 客户状态
}
