// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// GoodsSupplierRel is the golang structure for table goods_supplier_rel.
type GoodsSupplierRel struct {
	RelId       int64   `json:"relId"       ` // 关联ID
	GoodsId     int64   `json:"goodsId"     ` // 关联商品ID
	SupplierId  int64   `json:"supplierId"  ` // 关联供应商ID
	SupplyPrice float64 `json:"supplyPrice" ` // 供应价格
}
