// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Inventory is the golang structure for table inventory.
type Inventory struct {
	GoodsId   int64   `json:"goodsId"   ` // 库存商品ID
	GoodsCost float64 `json:"goodsCost" ` // 商品成本
	Quantity  int     `json:"quantity"  ` // 库存数量
}
