// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// OrderItem is the golang structure for table order_item.
type OrderItem struct {
	OrderId  int64   `json:"orderId"  ` // 单据ID
	GoodsId  int64   `json:"goodsId"  ` // 商品ID
	Price    float64 `json:"price"    ` // 出/入库单价
	Amount   float64 `json:"amount"   ` // 订单项总价格
	Quantity int     `json:"quantity" ` // 出/入库数量
	Notes    string  `json:"notes"    ` // 备注
}
