// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Order is the golang structure for table order.
type Order struct {
	OrderId           int64       `json:"orderId"           ` // 订单ID
	OrderNum          string      `json:"orderNum"          ` // 订单号
	OrderTime         *gtime.Time `json:"orderTime"         ` // 订单时间
	OrderType         int         `json:"orderType"         ` // 订单类型
	OrderSupplier     int64       `json:"orderSupplier"     ` // 订单供应商
	OrderSupplierName string      `json:"orderSupplierName" ` // 订单供应商名称
	OrderCustomer     int64       `json:"orderCustomer"     ` // 订单客户
	OrderCustomerName string      `json:"orderCustomerName" ` // 订单客户名称
	OrderAmount       float64     `json:"orderAmount"       ` // 订单总额
	OrderStatus       int         `json:"orderStatus"       ` // 订单状态
}
