// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ReturnOrder is the golang structure for table return_order.
type ReturnOrder struct {
	OrderId          int64       `json:"orderId"          ` // 单据ID
	OrderNo          string      `json:"orderNo"          ` // 单号
	OrderType        int         `json:"orderType"        ` // 单据类型
	POrderNo         string      `json:"pOrderNo"         ` // 源单据号
	OrderAmount      float64     `json:"orderAmount"      ` // 退货总金额
	OrderQuantity    int         `json:"orderQuantity"    ` // 退货总数
	CreateTime       *gtime.Time `json:"createTime"       ` // 制单时间
	CreateUser       int64       `json:"createUser"       ` // 制单人
	CompleteTime     *gtime.Time `json:"completeTime"     ` // 完成时间
	CompleteUser     int64       `json:"completeUser"     ` // 操作员
	Notes            string      `json:"notes"            ` // 备注
	OrderStatus      int         `json:"orderStatus"      ` // 单据状态
	CreateUserName   string      `json:"createUserName"   ` // 制单人姓名
	CompleteUserName string      `json:"completeUserName" ` // 完成人姓名
}
