// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Supplier is the golang structure for table supplier.
type Supplier struct {
	SupplierId        int64  `json:"supplierId"        ` // 供应商ID
	SupplierName      string `json:"supplierName"      ` // 供应商名称
	SupplierDesc      string `json:"supplierDesc"      ` // 供应商描述
	SupplierTelephone string `json:"supplierTelephone" ` // 供应商座机号码
	SupplierPhone     string `json:"supplierPhone"     ` // 供应商手机号码
	SupplierAddress   string `json:"supplierAddress"   ` // 供应商地址
	SupplierStatus    int    `json:"supplierStatus"    ` // 供应商状态
}
