// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SysRole is the golang structure for table sys_role.
type SysRole struct {
	RoleId     int64  `json:"roleId"     description:"角色ID，主键"` // 角色ID，主键
	RoleName   string `json:"roleName"   description:"角色名称"`    // 角色名称
	RoleStatus uint   `json:"roleStatus" description:"角色状态"`    // 角色状态
}
