// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SysRole is the golang structure for table sys_role.
type SysRole struct {
	RoleId   int64  `json:"roleId"   ` // 角色ID，主键
	RoleName string `json:"roleName" ` // 角色名称
}
