// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SysUser is the golang structure for table sys_user.
type SysUser struct {
	UserId       int64  `json:"userId"       ` // 用户ID，主键
	UserName     string `json:"userName"     ` // 登录用户名
	UserPassword string `json:"userPassword" ` // 登录密码，md5加密
	UserRealName string `json:"userRealName" ` // 用户真实姓名
	UserPhone    string `json:"userPhone"    ` // 用户手机号，11位数字
	UserImage    string `json:"userImage"    ` // 用户头像url
	UserStatus   uint   `json:"userStatus"   ` // 用户状态
}
