// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SysUserRole is the golang structure for table sys_user_role.
type SysUserRole struct {
	UserRoleId int64 `json:"userRoleId" ` // 用户角色关联ID
	UserId     int64 `json:"userId"     ` // 关联用户
	RoleId     int64 `json:"roleId"     ` // 关联角色
}
