// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SysAccess is the golang structure for table sys_access.
type SysAccess struct {
	AccessId    int64  `json:"accessId"    ` // 权限ID
	AccessTitle string `json:"accessTitle" ` // 权限标题
	AccessUri   string `json:"accessUri"   ` // 权限路径
}
