// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SysFile is the golang structure for table sys_file.
type SysFile struct {
	FileMd5  string `json:"fileMd5"  ` // 文件MD5
	FileName string `json:"fileName" ` // 文件名(UUID)
}
