// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SysRoleAccess is the golang structure for table sys_role_access.
type SysRoleAccess struct {
	RoleAccessId int64 `json:"roleAccessId" ` // 角色权限关联ID
	RoleId       int64 `json:"roleId"       ` // 关联角色ID
	AccessId     int64 `json:"accessId"     ` // 关联权限ID
}
